core/apis/urls.py
from django.urls import path
from . import views

app_name = 'apis'

urlpatterns = [
    path('', views.PingAPI.as_view(), name='ping'),
]

# auth and user api endpoints
urlpatterns += [
    path('login/', views.LoginAPI.as_view(), name='login'),
    path('register/', views.RegisterAPI.as_view(), name='register'),
    path('logout/', views.LogoutAPI.as_view(), name='logout'),
    path('userprofile/', views.UserProfileAPIView.as_view(), name='userprofile'),
    path('verifyotp/', views.VerifyOTPAPI.as_view(), name='verifyotp'),
    path('changepassword/', views.ChangePasswordAPIView.as_view(), name='changepassword'),
    path('resetpassword/', views.ResetPasswordAPIView.as_view(), name='resetpassword'),
]


# reports api endpoints
urlpatterns += [
    path('reports/', views.SubmittedReportsAPIView.as_view(), name='reports'),
    path('schools/', views.SchoolsAPIView.as_view(), name='schools'),
    path('dashboard/', views.DashboardAPIView.as_view(), name='dashboard'),
]

core/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-v1/', include('apis.urls')),
    path('', include('dashboard.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]


# Let django serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.LoginView.as_view(), name='login'),
    path('auth/delete-account', views.AccountDeletionView.as_view(), name='delete_account'),  #noqa
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

# dashboard urls
urlpatterns += [
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
]


# profile settings
urlpatterns += [
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('settings/preference', views.PreferenceSettingsView.as_view(), name='prefered_settings'), #noqa
    path('settings/password-reset', views.PasswordResetView.as_view(), name='password_reset'), #noqa
    path('settings/change-profile-pic', views.ChangeProfilePicView.as_view(), name='change_profile_pic'), #noqa
]

# reports
urlpatterns += [
    path('reports/', views.ReportView.as_view(), name='reports'),
    path('verify-reports/', views.VerifyReportView.as_view(), name='verify_report'),
    path('download-reports/', views.DownloadReportsView.as_view(), name='download_reports'),
]

# schools
urlpatterns += [
    path('schools/', views.SchoolsView.as_view(), name='schools'),
    path('delete-school/', views.DeleteSchoolView.as_view(), name='delete_school'),
    path('create-update-school/', views.CreateUpdateSchoolView.as_view(), name='create_update_school'),
    path('download-schools/', views.DownloadSchoolsView.as_view(), name='download_schools'),
]


# users
urlpatterns += [
    path('users/', views.UsersView.as_view(), name='users'),
    path('user-details/', views.UserDetailsView.as_view(), name='user_details'),
    path('create-update-user/', views.CreateUpdateUser.as_view(), name='create_update_user'), #noqa
    path('update-user-pic/', views.UpdateUserProfilePicView.as_view(), name='update_profile_pic'), #noqa
    path('download-users/', views.DownloadUsersView.as_view(), name='download_users'), #noqa

    path('add-user-to-group/', views.AddUserToGroupsView.as_view(), name='add_user_to_group'), #noqa
    path('add-perm-to-user/', views.AddPermsToUserView.as_view(), name='add_perm_to_user'), #noqa
]


# notifications
urlpatterns += [
    path('notifications/', views.NotificationsView.as_view(), name='notifications'),
    path('download-notifications/', views.DownloadNotificationsView.as_view(), name='download_notifications')
]

core/dashboard/models.py
from django.db import models

# Create your models here.

core/dashboard/forms.py
from django import forms

from apis.models import School


class SchoolForm(forms.ModelForm):
    '''forms to add schools'''
    
    class Meta:
        model = School
        exclude = ['created_at', 'updated_at']

core/apis/views/dashboard.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from apis.models import Report, Notification
from apis.serializers import NotificationSerializer
from datetime import datetime, timedelta


class PingAPI(APIView):
    '''This view is used to check if the server is up and running'''
    def get(self, request):
        '''This method is used to check if the server is up and running'''
        return Response({'message': 'pong'}, status=status.HTTP_200_OK)


class DashboardAPIView(APIView):
    '''This view is used to get the dashboard data'''
    
    def get(self, request):
        '''This method is used to get the dashboard data'''
        user = request.user
        reports = Report.objects.filter(reported_by=user)
        notifications = Notification.objects.filter(reporter=user)
        
        # Get today's date
        today = datetime.today().date()
        
        # Determine the next reporting day (Monday - Friday)
        if today.weekday() == 4:  # Friday
            next_reporting_day = today + timedelta(days=3)  # Monday
        elif today.weekday() in [5, 6]:  # Saturday or Sunday
            next_reporting_day = today + timedelta(days=(7 - today.weekday()))  # Monday
        else:
            next_reporting_day = today + timedelta(days=1)  # Next weekday
        
        return Response({
            'reports': reports.count(),  # Total reports submitted by the user
            'total_reports': 54,  # Total reports in a year
            'next_reporting_day': next_reporting_day.strftime('%Y-%m-%d'),  # Next reporting date
            'notifications': NotificationSerializer(notifications, many=True).data
        }, status=status.HTTP_200_OK)

# class DashboardAPIView(APIView):
#     '''This view is used to get the dashboard data'''
#     def get(self, request):
#         '''This method is used to get the dashboard data'''
#         user = request.user
#         reports = Report.objects.filter(reported_by=user)
#         notifications = Notification.objects.filter(reporter=user)
#         # look for the next reporting day's date (Mon - Fri)
#         # if today is Friday, then the next reporting day is Monday
#         # if today is Monday, then the next reporting day is Tuesday
#         # if today is Tuesday, then the next reporting day is Wednesday
#         # if today is Wednesday, then the next reporting day is Thursday
#         # if today is Thursday, then the next reporting day is Friday
#         # if today is Saturday, then the next reporting day is Monday
#         # if today is Sunday, then the next reporting day is Monday
        
#         return Response({
#             'reports': reports.count(), # total reports submitted by the user
#             'total_reports': 54, # total reports in a year
#             'notifications': NotificationSerializer(notifications, many=True).data
#         }, status=status.HTTP_200_OK)

core/dashboard/views/dashboard.py
from django.db.models import Sum
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.utils import timezone

from accounts.models import User
from apis.models import Report, School
from core.utils.contants import ReportStatus
from core.utils.decorators import StaffLoginRequired


class DashboardView(View):
    template = 'dashboard/pages/dashboard.html'

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        # totals
        total_users = User.objects.count()
        total_schools = School.objects.count()
        total_reports = Report.objects.count()

        # aggregates
        reports_this_week = Report.objects.filter(created_at__week=timezone.now().isocalendar()[1]).count()
        reports_this_month = Report.objects.filter(created_at__month=timezone.now().month).count()
        
        verified_reports_this_week = Report.objects.filter(created_at__week=timezone.now().isocalendar()[1], status=ReportStatus.APPROVED.value).count()
        verified_reports_this_month = Report.objects.filter(created_at__month=timezone.now().month, status=ReportStatus.APPROVED.value).count()

        # counst for the months
        months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
        # count the reports created in each month from jan-dec in a list
        reports_per_month = []
        verified_reports_per_month = []
        for month in range(1, 13):
            reports_per_month.append(Report.objects.filter(created_at__month=month).count())
            verified_reports_per_month.append(Report.objects.filter(created_at__month=month, status=ReportStatus.APPROVED.value).count())
        print("RPM", reports_per_month)
        print("VRPM", verified_reports_per_month)
        context ={
            'total_users': total_users,
            'total_schools': total_schools,
            'total_reports': total_reports,
            'reports_this_week': reports_this_week,
            'reports_this_month': reports_this_month,
            'verified_reports_this_week': verified_reports_this_week,
            'verified_reports_this_month': verified_reports_this_month,
            'reports_per_month': reports_per_month,
            'verified_reports_per_month': verified_reports_per_month,
            # 'reports_per_month': "|".join([str(i) for i in reports_per_month]),
            # 'verified_reports_per_month': "|".join([str(i) for i in verified_reports_per_month]),
            'months': months,
        }
        return render(request, self.template, context)

core/dashboard/views/login.py
from django.shortcuts import render, redirect
from django.views import View


from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from accounts.models import User


class LoginView(View):
    '''Login view'''
    template_name = 'accounts/login.html'

    def get(self, request):
        '''Handles GET requests'''
        return render(request, self.template_name)

    def post(self, request):
        '''Handles POST requests'''
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            # reset the login attempt
            messages.success(request, f'Welcome, {user.name.split(" ")[0].capitalize()}!')
            return redirect('dashboard:dashboard')
        else:
            messages.info(request, 'Invalid Username or Password')
            return render(request, self.template_name)
        

class LogoutView(View):
    '''Logout view'''
    def get(self, request):
        '''Handles GET requests'''
        logout(request)
        return redirect('dashboard:login')
    

class AccountDeletionView(View):
    '''Account deletion view'''
    def get(self, request):
        '''Handles GET requests'''
        return render(request, 'accounts/delete_account.html')

    def post(self, request):
        '''Handles POST requests for account deletion'''

        # delay for 2 seconds to simulate processing time
        import time
        time.sleep(2)
       
        messages.success(request, 'We have received your request to delete your account. We will process and get back to you shortly.')
       
        return redirect('dashboard:delete_account')
        

core/dashboard/views/notifications.py
import csv
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from apis.models import Notification
from core.utils.decorators import StaffLoginRequired
from django.utils.decorators import method_decorator
from django.db.models import Q

class NotificationsView(View):
    '''notifications view'''
    template = 'dashboard/pages/notifications.html'

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        '''gets all notifications'''
        query = request.GET.get('query')
        notifications = Notification.objects.all().order_by('-created_at')
        if query:
            notifications = Notification.objects.filter(
                Q(reporter__name__icontains=query)|
                Q(message__icontains=query)
            )
        context = {
            "notifications": notifications
        }
        return render(request, self.template, context)
    
class DownloadNotificationsView(View):
    '''Download notifications as csv'''

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        notifications = Notification.objects.all()
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="notifications.csv"'
        writer = csv.writer(response)
        writer.writerow(['ID', 'Reporter', 'Message', 'Created At']) # noqa
        for notification in notifications:
            writer.writerow([notification.id, notification.reporter.name, notification.message, notification.created_at])
        return response

core/dashboard/views/reports.py
import csv
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from apis.models import Report
from django.db.models import Q
from core.utils.contants import ReportStatus
from core.utils.decorators import StaffLoginRequired
from django.utils.decorators import method_decorator

from django.contrib import messages


class ReportView(View):
    template = 'dashboard/pages/reports.html'

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        query = request.GET.get('query')
        print(f"query: {query}")
        filtered = request.GET.get('form_id') == 'filter'
        reports = Report.objects.all().order_by('created_at')
        if query:
            reports = Report.objects.filter(
                Q(report_id__icontains=query)|
                Q(school__name__icontains=query)|
                Q(meal_type__icontains=query)|
                Q(comments__icontains=query)|
                Q(reported_by__name__icontains=query)|
                Q(status__icontains=query)
            ).order_by('created_at')

        if filtered:
            print('Filtered!!')
            report_status = request.GET.get('status')
            report_date = request.GET.get('report_date')
            created_at = request.GET.get('created_date')

            if report_status == '' or str(report_status).upper() == 'ALL':
                pass
            else:
                reports = reports.filter(status=report_status)
            if report_date:
                reports = reports.filter(date_of_report=report_date)
            if created_at:
                reports = reports.filter(created_at=created_at)

        context = {
            'reports': reports,
        }
        return render(request, self.template, context)

    def post(self, request):
        return redirect('reports')
    
class VerifyReportView(View):
    '''used to verify the reports submitted'''
    template = 'dashboard/pages/verify-report.html'

    @method_decorator(StaffLoginRequired)
    def get(self, request, *args, **kwargs):
        query = request.GET.get('query')
        report = Report.objects.filter(report_id=query).first()
        context = {
                'report': report
        }
        return render(request, self.template, context)
    
    @method_decorator(StaffLoginRequired)
    def post(self, request):
        '''used to process the report: approve, reject, etc...'''

        report_id = request.POST.get('report_id')
        report_status = request.POST.get('status')
        report = Report.objects.filter(report_id=report_id).first()
        if not report:
            # somehow report wasn't found
            messages.success(request, "Couldn not find report")
            return redirect('dashboard:reports')
        approved_statuses = [ReportStatus.PENDING_REVIEW.value, ReportStatus.APPROVED.value, ReportStatus.REJECTED.value, ]
        if report_status in approved_statuses:
            report.status = report_status
            report.save()
            messages.success(request, "Report Processing Completed Succesfully")
        else:
            messages.error(request, "Selected status not allowed")
        return redirect('dashboard:reports')
    


class DownloadReportsView(View):
    '''Download reports as csv'''

    @method_decorator(StaffLoginRequired)
    def get(self, request):
        reports = Report.objects.all()
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="reports.csv"'
        writer = csv.writer(response)
        writer.writerow(['Report ID', 'School', 'Students Enrolled', 'Students Fed', 'Meal Type', 'Comments', 'Status', 'Reported By', 'Created At']) # noqa
        for report in reports:
            writer.writerow([report.report_id, report.school.name, report.students_enrolled, report.students_fed, report.meal_type, report.comments, report.status, report.reported_by.name, report.created_at])
        return response

core/dashboard/templates/includes/dashboard_header.html
{% load static %}
<!-- Header -->
<div class="header header-one">

    <!-- Sidebar Toggle -->
    <a href="javascript:void(0);" id="toggle_btn">
            <span class="toggle-bars">
                <span class="bar-icons"></span>
                <span class="bar-icons"></span>
                <span class="bar-icons"></span>
                <span class="bar-icons"></span>
            </span>
        </a>
    <!-- /Sidebar Toggle -->

    <!-- Search -->
    <div class="top-nav-search">
        <form>
            <input type="text" class="form-control" placeholder="Search here">
            <button class="btn" type="submit"><img src="{% static 'dashboard/img/icons/search.svg' %}" alt="img"></button>
        </form>
    </div>
    <!-- /Search -->

    <!-- Mobile Menu Toggle -->
    <a class="mobile_btn" id="mobile_btn">
            <i class="fas fa-bars"></i>
        </a>
    <!-- /Mobile Menu Toggle -->

    <!-- Header Menu -->
    <ul class="nav nav-tabs user-menu">
        
        <li class="nav-item dropdown  flag-nav dropdown-heads">
            <a class="nav-link" data-bs-toggle="dropdown" href="#" role="button">
                    <i class="fe fe-bell"></i> <span class="badge rounded-pill"></span>
                </a>
            <div class="dropdown-menu notifications">
                <div class="topnav-dropdown-header">
                    <span class="notification-title">Notifications</span>
                    <a href="javascript:void(0)" class="clear-noti"> Clear All</a>
                </div>
                <div class="noti-content">
                    <ul class="notification-list">
                    </ul>
                </div>
                <div class="topnav-dropdown-footer">
                    <a href="">View all Notifications</a>
                </div>
            </div>
        </li>
        <li class="nav-item  has-arrow dropdown-heads ">
            <a href="javascript:void(0);" class="win-maximize">
                    <i class="fe fe-maximize"></i>
                </a>
        </li>
        <!-- User Menu -->
        <li class="nav-item dropdown">
            <a href="javascript:void(0)" class="user-link  nav-link" data-bs-toggle="dropdown">
                    <span class="user-img">
                        <img src="{% if user.avatar %} {{user.avatar.url}} {% else %} {% static 'dashboard/img/profiles/profile.png' %} {% endif %}" alt="img" class="profilesidebar">
                        <span class="animate-circle"></span>
                    </span>
                    <span class="user-content">
                        {% if request.user %}
                        <span class="user-name">{{request.user.email}}</span>
                        {% else %}
                        <span class="user-name">Guest</span>
                        {% endif %}
                    </span>
                </a>
            <div class="dropdown-menu menu-drop-user">
                <div class="profilemenu">
                    <div class="subscription-menu">
                        <ul>
                            <li>
                                <a class="dropdown-item" href="{% url 'dashboard:settings' %}">Settings</a>
                            </li>
                        </ul>
                    </div>
                    <div class="subscription-logout">
                        <ul>
                            <li class="pb-0">
                                <a class="dropdown-item" href="{% url 'dashboard:logout' %}">Log Out</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </li>
        <!-- /User Menu -->

    </ul>

    <!-- /Header Menu -->

    
{% for message in messages %}
<div class="row">
    <div class="col-12">
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
    </div>
</div>
{% endfor %}

</div>
<!-- /Header -->

<!-- message -->

core/dashboard/templates/includes/sidebar.html
{% load static %}
<!-- Sidebar -->
<div class="sidebar" id="sidebar" style="overflow-y: scroll;">
    <div class="sidebar-header">
        <div class="sidebar-logo">
            <a href="{% url 'dashboard:dashboard' %}">
                    <img class="logo-default" src="{% static 'dashboard/img/pkay-logo-white.png' %}" style="height: 150px;" alt=""/>
                </a>
            <a href="{% url 'dashboard:dashboard' %}">
                    <img src="{% static 'dashboard/img/pkay-logo-white.png' %}" class="img-fluid logo-small" alt="">
                </a>
        </div>
    </div>
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            <!-- Main -->
            <ul>
                <li class="menu-title"><span>Main</span></li>
                <li class="">
                    <a href="{% url 'dashboard:dashboard' %}"><i class="fe fe-home"></i> <span> Dashboard</span> <span class="menu-arrow"></span></a>
                </li>
            </ul>
            <!-- /Main -->

            <!-- Customers -->
            <ul>
                <li class="menu-title"><span>Management</span></li>
                <li>
                    <a href="{% url 'dashboard:reports' %}"><i class="fe fe-users"></i> <span>Reports</span></a>
                </li>
                <li>
                    <a href="{% url 'dashboard:schools' %}"><i class="fe fe-home"></i> <span>Schools</span></a>
                </li>
            </ul>
            <!-- /Customers -->

            <!-- Purchases -->
            <ul>
                <li class="menu-title"><span>Notifications</span></li>
                <li>
                    <a href="{% url 'dashboard:notifications' %}"><i class="fe fe-shopping-cart"></i> <span>Notifications</span></a>
                </li>
            </ul>
            <!-- /Purchases -->

            <!-- User Management -->
            <ul>
                <li class="menu-title"><span>User Management</span></li>
                <li class="submenu">
                    <a href="#"><i class="fe fe-user"></i> <span> Manage Users</span> <span class="menu-arrow"></span></a>
                    <ul>
                        <li><a href="{% url 'dashboard:users' %}">Users</a></li>
                    </ul>
                </li>
            </ul>
            <!-- /User Management -->

            <!-- Settings -->
            <ul>
                <li class="menu-title"><span>Settings</span></li>
                <li>
                    <a href="{% url 'dashboard:settings' %}"><i class="fe fe-settings"></i> <span>Settings</span></a>
                </li>
                <li>
                    <a href="{% url 'dashboard:logout' %}"><i class="fe fe-power"></i> <span>Logout</span></a>
                </li>
            </ul>
            <!-- /Settings -->

        </div>
    </div>
</div>
<!-- /Sidebar -->